version: "3.3"
services:
  kucoin-api:
      build: .
      restart: always
      privileged: true
      container_name: kucoin-api
      logging:
        driver: "json-file"
        options:
          max-size: 10m
          max-file: "3"
          labels: "production_status"
          env: "os"
      labels:
        production_status: "testing"
      environment:
        - os=ubuntu
      volumes:
        - /root/projects/trading/kucoin-api:/usr/src/app/kucoin